# These are supported funding model platforms

github: [softvar] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: softvar # Replace with a single Patreon username
open_collective: softvar # Replace with a single Open Collective username
custom: ['https://paypal.me/softvar'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
